# Data transformation

## Understanding the Raw Data

The raw data was in a zipped format of .pgn.bz2. The unzipped .pgn file was then converted through [read.py](https://github.com/ww2615/chessgame_analysis/blob/main/code/read.py).

The result of this transformation was named "data_index.csv" each constituting of 10,000,000 lines. Naturally, there were 9 files since the total count of games in the original data was 88,092,721.

**Each row** represented a **game** with columns Result[^1], UTCDate[^2], UTCTime[^3], WhiteElo[^4], BlackElo[^5], WhiteRatingDiff[^6], BlackRatingDiff[^7], ECO[^8], TimeControl[^9], Termination[^10], Evaluation[^11].

This "data_index.csv" was only generated to answer the following questions.

- What items are missing in the original data?
- How much games were annotated?

The answer to the first question will be answered in the next chapter.
From the data, we deduced that 7,142,630 / 88,092,721 = **8.1** % of the games were annotated compared to the **6** % claimed on the [website](https://database.lichess.org/#standard_games).

## Formatting the Raw Data

We decided to focus on the **7,142,630** games that were annotated.

The first formatting process was done using [eval.py](https://github.com/ww2615/chessgame_analysis/blob/main/code/eval.py).

This process was different from the read.py that the resulting csv(pgn_index.csv) from eval.py contained the PGN descriptions of every game played.

This process was conducted to generate a working **csv dataset** independent from the original dataset.



The second formatting process used [edit.py](https://github.com/ww2615/chessgame_analysis/blob/main/code/edit.py).

The formatting process intended to change **each row** to **moves** instead of **games**.

Each **move** was associated with Result[^1], WhiteElo[^4], BlackElo[^5], ECO[^8], TimeControl[^9], Termination[^10], Color[^12], MoveNum[^13], Move[^14], Type[^15], Eval[^16], EvalDiff[^17], Time[^18], TimeSpent[^19].

The missing data of this csv data set will be examined in the next chapter.



[^1]: Result of the game.
[^2]: UTC date of the game.
[^3]: UTC time of the game.
[^4]: White player's Elo in Lichess.
[^5]: Black player's Elo in Lichess.
[^6]: Change in White player's Elo after the game.
[^7]: Change in Black player's Elo after the game.
[^8]: Encyclopedia of Chess Openings. The Opening that was played in the game.
[^9]: The time format in which the game was played. Ex) 10 minutes + 5 second increment = "600+5".
[^10]: How the game ended. Ex) Normal(checkmate or resignation), Abandoned(player left the game), Time Forfeit (player ran out of time).
[^11]: Whether or not the game was annotated.
[^12]: The color of the player that made the move.
[^13]: The number of the move.
[^14]: The algebraic notation of the move made. ex) Qh4.
[^15]: One of the seven types of move: blunder, mistake, dubious, normal, interesting, good, and brilliant.
[^16]: Computer evaluation after the move.
[^17]: The change in evaluation. It is 0 when the previous or current evaluation was forced mate (#number).
[^18]: Time left for the player.
[^19]: Time spent on the move.
