# Conclusion

## Results

## Limitations

There were several limits to our analysis.

1. The analysis was done exclusively on **600 + 0** Time Format.

From the previous section, we have discussed that this format is the most played time format on lichess.org and the elo of players were representative of the whole data set. However, it is still **17%** of the total games. There are other forms of chess games such as `hyper bullet` (less than 1 minute), `bullet` (1 - 3 minute), `blitz` (less than 10 minutes), `rapid` (10 - 60 minutes), and `normal` (90 minutes). Analysis on these different categorizations of chess could have yielded interesting insights.

2. The data set was gathered over a **brief period**.

The data set was exclusively collected in **October 2021**. Considering the history of chess, the gameplay and strategies in chess do not change in a month. However, using the data from a longer period would have represented the gameplay in lichess.org better.

3. The data set was exclusively from **lichess.org**.

For online chess, there are other well-established platforms such as chess.com or chess24. Depending on the platform, there will be differences between player gameplay. However, chess24 and chess.com do not have API systems that would allow access to gameplay data. 

Limitations 1 and 2 were due to the technical limits of working on our computers. Without any form of database, it was hard to generate and share data between teammates that were easily over 10 GB.

## Future directions

The lichess database contains PGNs from 2013. Although there is a low chance that all the games are annotated, it would be interesting to conduct the study over the extensive amount of game data they own. Comparisons between the time controls would also yield interesting results. Since lichess database provides player profiles, studying a player's decision over time might also lead to fascinating insights. If players get to compare their strengths and weaknesses to the greater mass, they may have an easier time improving at chess and managing their time.

The best way to conduct future studies would be using databases and data manipulation languages such as SQL. Lichess.org is a nonprofit website running on donations and as a result, they don't store all of their games in a database. It would have been convenient if lichess.org provided APIs like tweepy. In multiple stages of our data transformation, using databases could have significantly improved the organization and manipulation of data. Filtering and mutating data would take far less effort.
